import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut, getSession } from 'next-auth/react'
import Router from 'next/router'

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const session = await getSession({ req })
  console.log(session)
  if (session) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    }
  }

  return {
    props: {},
  }
}

const Home: NextPage = () => {
  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session ? (
        <h1>Sign In to see your name!</h1>
      ) : (
        <h1>Hello {session.user?.name}</h1>
      )}

      {!session ? (
        <button onClick={() => signIn()}>Login</button>
      ) : (
        <button onClick={() => signOut()}>Log out</button>
      )}

      {!session ? 'Não autorizado' : <p>{session.user?.email}</p>}
      <button onClick={() => Router.push('/dashboard')}>Dashboard</button>
    </div>
  )
}

export default Home
